version: '3.8'
services:
  node-app:
    image: node:14
    container_name: lrfile-client-express
    working_dir: /app
    command: STAGE=dev node index.js
    ports:
      - "3000:3000"
    environment:
      # AWS_ACCESS_KEY_ID
      # AWS_SECRET_ACCESS_KEY
      # AWS_DEFAULT_REGION
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        # awslogs-group
        awslogs-create-group: "true"